### ISSUE TITLE
Extending OpenZeppelin's ERC20 as an abstract contract fails

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#65] opened 2021-09-01 14:09 UTC
```
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

abstract contract MyERC20 is ERC20 {
}
```

This fails with the error:
```
/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:16
    throw new Error(message);
    ^

Error: Mismatch in length between [VariableDeclaration#32,VariableDeclaration#34] of len 2 and [] of len 0
    at assert (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:16:11)
    at Object.zip (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/util/misc.js:195:5)
    at helper (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:104:24)
    at getAssignments (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:238:20)
    at getAssignments.next (<anonymous>)
    at Object.findAliasedStateVars (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/state_vars.js:272:21)
    at new InstrumentationContext (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/instrumenter/instrumentation_context.js:231:38)
    at Object.<anonymous> (/Users/alex/.nvm/versions/node/v16.8.0/lib/node_modules/eth-scribble/dist/bin/scribble.js:582:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Parsing `openzeppelin/contracts/token/ERC20/ERC20.sol` directly works with `scribble`, so `abstract` seems to have some relevance here.

**Comment by axic** [comment] 2021-09-08 09:32
@cd1m0 this seems to be a rather serious blocker for a lot of use cases.

**Comment by cd1m0** [comment] 2021-09-08 11:00
@axic - noted will prioritize. I think this is a duplicate of https://github.com/ConsenSys/scribble/issues/63 . Will re-try it after fixing that one and close accordingly if correct.

**Comment by cd1m0** [comment] 2021-09-14 10:27
I think this is a duplicate of #63 . The error message is the same, and after fixing #63 I can no longer reproduce it.

It also makes sense - in the abstract contract example you again have an `InheritanceSpecifier` with no arguments, whereas the base contract constructor expects 2 arguments, thus causing the failure

**Closed** 2021-09-14 10:28 UTC

**Comment by axic** [comment] 2021-09-14 11:26
Thanks, this seems to be working with `develop`.
