### ISSUE TITLE
Add support for function type in function parameter

### ISSUE THREAD

**Issue by ecp4224** [ConsenSys/scribble#155] opened 2022-02-23 15:57 UTC
It seems the [Solidity function type](https://docs.soliditylang.org/en/v0.8.11/types.html#function-types) is not supported by scribble. If my smart contract has a function with a function type in the parameter, scribble will throw the following error

```
Error: Unexpected ABI Type function (address) returns (bool)
    at assert (/home/edkek/.nvm/versions/node/v10.24.1/lib/node_modules/eth-scribble/node_modules/solc-typed-ast/dist/misc/utils.js:36:11)
    at abiTypeToLibraryCanonicalName (/home/edkek/.nvm/versions/node/v10.24.1/lib/node_modules/eth-scribble/node_modules/solc-typed-ast/dist/types/abi.js:122:23)
    at args.vParameters.vParameters.map (/home/edkek/.nvm/versions/node/v10.24.1/lib/node_modules/eth-scribble/node_modules/solc-typed-ast/dist/ast/implementation/declaration/function_definition.js:61:102)
    at Array.map (<anonymous>)
    ....
```

Minimum Reproducible Example

```solidity
contract Managed {
    address owner;
    mapping(address=>bool) admins;

    constructor() public {
        owner = msg.sender;
        admins[owner] = true;
    }

    modifier OwnerOnly {
        assert(owner == msg.sender);
        _;
    }

    modifier AdminOnly {
        assert(admins[msg.sender]);
        _;
    }

    /// #if_succeeds {:msg "only owner can add admins"} old(admins[msg.sender]);
    function addAdminInternal(address addr) internal returns (bool) {
        admins[addr] = true;
        return admins[addr];
    }
    
    function someComplexFunction(address caller, function (address) internal returns (bool) funcName) internal returns (bool) {
        return funcName(caller);
    } 

    function addAdmin(address newAdmin) public {
        someComplexFunction(newAdmin, addAdminInternal);
    }
}
```

**Comment by ecp4224** [comment] 2022-02-23 23:05
I can confirm that if any function declared anywhere in a smart contract uses the function type (even if the function is not being used directly by the annotated functions) will result in this error.

**Comment by cd1m0** [comment] 2022-03-12 01:55
Thank you for the bug report! The issue is an unimplemented feature in the [solc-typed-ast](https://github.com/ConsenSys/solc-typed-ast) library in the [abiTypeToLibraryCanonicalName](https://github.com/ConsenSys/solc-typed-ast/blob/master/src/types/abi.ts#L182) here:

```typescript
...
    if (t instanceof MappingType) {
        const keyName = abiTypeToLibraryCanonicalName(t.keyType);
        const valueName = abiTypeToLibraryCanonicalName(t.valueType);

        return `mapping(${keyName} => ${valueName})`;
    }

    assert(false, "Unexpected ABI Type: {0}", t);
```

In short we need to add support for converting function type names to abi strings in that file. Filed https://github.com/ConsenSys/solc-typed-ast/issues/103 to track this.

**Comment by blitz-1306** [comment] 2022-03-24 05:21
Part of this issue is addressed in https://github.com/ConsenSys/solc-typed-ast/issues/104 and is now part of [**solc-typed-ast** v9.1.0 release](https://github.com/ConsenSys/solc-typed-ast/releases/tag/v9.1.0). Further fix should be inmplemented on side of Scribble.

**Comment by cd1m0** [comment] 2022-03-30 05:44
We have now bumped solc-typed-ast to 9.1.1 in scribble's develop branch, and this will be part of version 0.6.6 which should be out today. With the current develop branch your sample works. Closing this for now - if there are any follow up issues please re-open this :). 

Thanks again for the report!

**Closed by cd1m0** 2022-03-30 05:44 UTC
