### ISSUE TITLE
Support Using For

### ISSUE THREAD

**Issue by newcodepusher** [ConsenSys/scribble#33] opened 2021-04-20 12:16 UTC
Сan you add support for similar solidity instructions?
[solidity using-for](https://docs.soliditylang.org/en/v0.5.3/contracts.html#using-for)

**Comment by cd1m0** [comment] 2021-04-22 22:48
Can you clarify what you mean for support for using-for or add a sample that you wish to be supported? When I try to instrument the following sample:

```
library L {
        function plusOne(uint x) internal pure returns (uint) {
                return x + 1;
        }
}

contract Foo {
        using L for uint;

        /// if_succeeds old(x).plusOne() == x;
        function inc(uint x) public returns (uint) {
                return x + 1;
        }
}
```

I get the following instrumented code, which seems correct:

```
pragma solidity 0.8.3;

library L {
    function plusOne(uint x) internal pure returns (uint) {
        return x + 1;
    }
}

contract Foo {
    using L for uint;

    event AssertionFailed(string message);

    struct vars0 {
        uint256 old_0;
    }

    function inc(uint x) public returns (uint RET_0) {
        vars0 memory _v;
        unchecked {
            _v.old_0 = x;
        }
        RET_0 = _original_Foo_inc(x);
        unchecked {
            if (!(_v.old_0.plusOne() == x)) {
                emit AssertionFailed("0: ");
                assert(false);
            }
        }
    }

    function _original_Foo_inc(uint x) private returns (uint) {
        return x + 1;
    }
}
/// Utility contract holding a stack counter
contract __scribble_ReentrancyUtils {
    bool __scribble_out_of_contract = true;
}
```

**Comment by newcodepusher** [comment] 2021-04-23 07:38
Your example works, but this one does not

```
pragma solidity >=0.6.0 <0.8.0;

library Token {
    function balanceOf(address x) internal pure returns (uint) {
        return 123;
    }
}

contract Foo {
    using Token for address;

    /// if_succeeds x.balanceOf() == 123;
    function inc(address x) public returns (uint) {
        return x.balanceOf();
    }
}
```

**Comment by cd1m0** [comment] 2021-05-05 02:17
The issue is that the typechecking logic below is too aggressive. The same problem would happen if the argument was `Foo x` instead of `address x` and we had `this.balanceOf()` in the expression. Fix coming in shortly, and will be merged in the next release.

https://github.com/ConsenSys/scribble/blob/6e737c9ff7db2e0466825411b86a810a6079f988/src/spec-lang/tc/typecheck.ts#L1559

**Closed** 2021-05-05 08:07 UTC
